import { useState } from 'react';
import { Bell, Save, School, ShieldCheck } from 'lucide-react';

export default function Settings() {
  const [saved, setSaved] = useState(false);
  const [settings, setSettings] = useState(() => JSON.parse(localStorage.getItem('school-settings') || '{"schoolName":"School Management","academicYear":"2026-27","email":"office@school.test","notifications":true}'));
  const update = (key, value) => setSettings(current => ({ ...current, [key]: value }));
  const save = event => { event.preventDefault(); localStorage.setItem('school-settings', JSON.stringify(settings)); setSaved(true); setTimeout(() => setSaved(false), 2500); };
  return <><div className="page-intro"><div><span className="eyebrow">ADMINISTRATION / PREFERENCES</span><h2>Settings</h2><p className="muted">Manage the school profile and local dashboard preferences.</p></div></div><form className="settings-layout" onSubmit={save}><section className="panel settings-panel"><div className="settings-heading"><School size={20} /><div><h3>School profile</h3><p className="muted">These details are stored locally for this demo.</p></div></div><label>School name<input value={settings.schoolName} onChange={event => update('schoolName', event.target.value)} /></label><label>Academic year<input value={settings.academicYear} onChange={event => update('academicYear', event.target.value)} /></label><label>Office email<input type="email" value={settings.email} onChange={event => update('email', event.target.value)} /></label></section><section className="panel settings-panel"><div className="settings-heading"><ShieldCheck size={20} /><div><h3>Preferences</h3><p className="muted">Choose how the administration workspace behaves.</p></div></div><label className="toggle-row"><span><b><Bell size={16} /> Activity notifications</b><small>Show updates in the admin workspace</small></span><input type="checkbox" checked={settings.notifications} onChange={event => update('notifications', event.target.checked)} /></label><div className="settings-note">Database connection is configured through the backend `.env` file.</div></section><div className="settings-actions">{saved && <span className="save-message">Settings saved</span>}<button className="primary-button"><Save size={16} /> Save settings</button></div></form></>;
}
